version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    level: DEBUG
    filename: app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  '':
    level: INFO
    handlers: [console, file_handler]
    propagate: false
  processor:
    level: INFO
    handlers: [console, file_handler]
    propagate: false
  storage:
    level: INFO
    handlers: [console, file_handler]
    propagate: false
  kafka:
    level: ERROR
    handlers: [file_handler]
